name: Enhancement
description: Suggest an enhancement to an existing feature in the CLI Todo App
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief description of the enhancement.
      placeholder: What existing feature would you like to enhance?
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: Describe how the feature currently works.
    validations:
      required: true

  - type: textarea
    id: desired
    attributes:
      label: Desired Behavior
      description: Describe how you would like the feature to work after the enhancement.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why would this enhancement be useful?
      placeholder: Explain the benefits or use cases for this enhancement.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: If you have ideas about how to implement this enhancement, describe them here.
      placeholder: Any thoughts on how this could be implemented?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the enhancement request here.
    validations:
      required: false