name: Feature Request
description: Suggest a new feature for the CLI Todo App
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief description of the feature request.
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: Describe the problem this feature would solve or the use case it would enable.
      placeholder: Is there a specific problem or use case this feature would address?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or implementation.
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Have you considered any alternative approaches?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false