name: Question / Support
description: Ask a question or request support for the CLI Todo App
title: "[Question]: "
labels: ["question", "help wanted"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What is your question or what support do you need?
      placeholder: Please provide a clear and detailed question.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to do or where you encountered this question.
      placeholder: What were you trying to accomplish when this question arose?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment.
      placeholder: |
        - OS: [e.g., Windows 10, macOS 11.2, Ubuntu 20.04]
        - CLI Todo App Version: [e.g., 1.0.0]
        - Node.js/Python Version: [if applicable]
        - Any other relevant environment details
    validations:
      required: false

  - type: textarea
    id: attempts
    attributes:
      label: What have you tried?
      description: Describe any steps you've already taken to solve this issue.
      placeholder: Have you looked at the documentation? Tried any workarounds?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information that might be helpful.
    validations:
      required: false